### ISSUE TITLE
Remove Spaces in xcconfig file names

### ISSUE THREAD

**Issue by schwa** [dempseyatgithub/BuildSettingExtractor#42]
My target is named "Foo Bar iOS". I'd like my .xcconfig files to be named "Foo-Bar-iOS".

**Comment by dempseyatgithub** [comment]
Thanks for filing the issue @schwa. Were you thinking this would be a preference? Or just something that happens automatically?

I haven't had a chance to test since you filed the issue, but does Xcode choke on .xcconfig files with spaces?

Note to self: this should just be a matter of using `-stringByReplacingOccurrencesOfString:withString:` in `-configFilenameWithTargetName:configName:`

**Comment by dempseyatgithub** [comment]
Xcode 11 does not seem to choke if an xcconfig file has a space in its filename. Having a space would be more of a pain in specifying an xcconfig file on the command line.

Currently leaning towards this happening automatically without a preference and without alerting the user.
